### ISSUE TITLE
update skins with stuff please

### ISSUE THREAD

**Issue by Goten87** [jamiebicknell/Minecraft-Avatar#9]
can u update the skins.php file to have it that we can say we want all sides or a spesific side like front
i want to use this in my player list on my website but only want to show the front of the char
but i cant resize the img to show only 1 its having the width of all 4 sides
if i only show the front of my skin i want to resize the img as well to that

**Comment by jamiebicknell** [comment]
Depending on the skin type, the total width of the front can change, so it's not as simple as just trimming the image to the front because the image widths would be inconsistent.

This isn't a feature I'll be adding. You're 95% there with just showing the front, you just need to adjust the width logic.
